name: builder
on:
  push:
  schedule:
    - cron: '0 6 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}
      
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        context: .
        file: ./Dockerfile
        tags: |
          ghcr.io/netbootxyz/${{ github.workflow }}:latest
          ghcr.io/netbootxyz/${{ github.workflow }}:${{ github.sha }}
